/**
 * Renders `report.html` at the repo root — the committed reference document for
 * the relay: how it works, how it is built, what it promises about security and
 * retention, an example run against production, and a self-hosting guide.
 *
 * It is regenerated by every full playground run, so the example figures in it
 * are always real measurements rather than claims.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileFlow, handshake, stateMap, topology } from './diagrams.mjs'
import { bytes, duration } from './log.mjs'

const QR_ILLUSTRATION = 'https://cdn.wolffi.sh/generic/qr.png'

const esc = (s) =>
  String(s ?? '').replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]
  )

const code = (body) => `<div class="wrap"><pre>${esc(body.trim())}</pre></div>`

export async function writeReport({ log, ctx, outDir, repoRoot }) {
  const run = {
    startedAt: log.startedAt,
    generatedAt: new Date(log.startedAt).toISOString(),
    totalMs: log.totalMs,
    relayUrl: ctx.relayUrl,
    rid: ctx.rid,
    handshakeMs: ctx.handshakeMs,
    passed: log.passed,
    failed: log.failed,
    quick: Boolean(ctx.options?.quick),
    phases: log.phases.map((p) => ({
      title: p.title,
      detail: p.detail,
      ms: p.ms,
      checks: p.checks
    })),
    checks: log.checks,
    transfers: log.transfers,
    evidence: log.evidence.find((e) => e.kind === 'wire') ?? null,
    results: ctx.results,
    log: log.lines
  }

  await fs.writeFile(path.join(outDir, 'run.json'), JSON.stringify(run, null, 2))
  await fs.writeFile(
    path.join(outDir, 'run.log'),
    log.lines.map((l) => `${(l.at / 1000).toFixed(2)}s [${l.actor}] ${l.message}`).join('\n')
  )

  const file = path.join(repoRoot, 'report.html')
  await fs.writeFile(file, renderReference(run))
  return file
}

export function renderReference(run) {
  const ok = run.failed === 0
  const totals = run.results?.totals ?? {}
  const big = run.results?.bigFile

  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="color-scheme" content="dark light" />
<meta name="theme-color" content="#040a18" />
<title>Wolffish Relay — how it works, what it promises, how to run your own</title>
<meta name="description" content="Reference for the Wolffish tunnel relay: architecture, security model, zero-retention guarantees, a verified example run, and a self-hosting guide." />
<link rel="icon" type="image/png" href="https://cdn.wolffi.sh/generic/icon.png" />
<style>
  :root{
    --bg:#0a0f1b; --fg:#e8edf5; --muted:#93a1b8; --line:rgba(147,161,184,.18);
    --card:rgba(147,161,184,.06); --ok:#34d399; --bad:#f87171; --accent:#6ea8fe;
    --shadow:rgba(0,0,0,.5);
  }
  @media (prefers-color-scheme: light){
    :root{ --bg:#f7f9fc; --fg:#141b26; --muted:#5a6b82; --line:rgba(20,27,38,.13);
      --card:rgba(20,27,38,.04); --ok:#059669; --bad:#dc2626; --accent:#2563eb;
      --shadow:rgba(20,27,38,.15); }
  }
  *{margin:0;padding:0;box-sizing:border-box}
  html{scroll-behavior:smooth}
  body{background:var(--bg);color:var(--fg);
    font:16px/1.7 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;
    -webkit-font-smoothing:antialiased;padding:3rem 1.25rem 5rem}
  main{max-width:56rem;margin:0 auto}
  h1{font-size:2rem;letter-spacing:-.025em;line-height:1.25}
  h2{font-size:1.35rem;letter-spacing:-.02em;margin:3.5rem 0 .5rem;scroll-margin-top:1rem}
  h3{font-size:1.02rem;margin:2rem 0 .5rem}
  p{margin:.85rem 0}
  a{color:var(--accent)}
  .lede{color:var(--muted);font-size:1.05rem;margin-top:.6rem}
  .muted{color:var(--muted)}
  .rule{height:1px;background:var(--line);border:0;margin:2.5rem 0}
  header .badges{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:1.1rem}
  .badge{display:inline-flex;align-items:center;gap:.4rem;padding:.3rem .8rem;border-radius:999px;
    font-size:.82rem;font-weight:600;border:1px solid var(--line);background:var(--card);color:var(--muted)}
  .badge.pass{background:rgba(52,211,153,.14);color:var(--ok);border-color:transparent}
  .badge.fail{background:rgba(248,113,113,.14);color:var(--bad);border-color:transparent}
  .dot{width:.5rem;height:.5rem;border-radius:50%;background:currentColor}
  nav.toc{border:1px solid var(--line);background:var(--card);border-radius:14px;padding:1rem 1.25rem;margin-top:2rem}
  nav.toc ol{margin:0;padding-left:1.2rem;columns:2;column-gap:2rem}
  nav.toc li{margin:.2rem 0;font-size:.92rem}
  @media (max-width:38rem){nav.toc ol{columns:1}}
  .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(9rem,1fr));gap:.7rem;margin:1.25rem 0}
  .card{border:1px solid var(--line);background:var(--card);border-radius:12px;padding:.85rem 1rem}
  .card .k{font-size:.7rem;text-transform:uppercase;letter-spacing:.09em;color:var(--muted)}
  .card .v{font-size:1.2rem;font-weight:650;margin-top:.15rem}
  .wrap{overflow-x:auto;border:1px solid var(--line);border-radius:12px;background:var(--card);margin:1rem 0}
  table{width:100%;border-collapse:collapse;font-size:.9rem}
  th,td{text-align:left;padding:.55rem .7rem;border-bottom:1px solid var(--line);vertical-align:top}
  tr:last-child td{border-bottom:0}
  th{font-size:.7rem;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);font-weight:600}
  td.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
  code,pre,.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
  code{font-size:.86em;background:var(--card);border:1px solid var(--line);border-radius:5px;padding:.08em .35em}
  pre{padding:1rem;overflow-x:auto;font-size:.82rem;line-height:1.55;white-space:pre;color:var(--fg)}
  pre code{background:none;border:0;padding:0}
  .ok{color:var(--ok)}.bad{color:var(--bad)}.accent{color:var(--accent)}
  figure{margin:1.5rem 0}
  figure svg{width:100%;height:auto;display:block;border:1px solid var(--line);border-radius:14px;
    background:var(--card);padding:.75rem}
  figcaption{color:var(--muted);font-size:.85rem;margin-top:.5rem;text-align:center}
  .d-title{fill:var(--fg);font:600 15px ui-sans-serif,system-ui,sans-serif}
  .d-sub{fill:var(--muted);font:13px ui-sans-serif,system-ui,sans-serif}
  .d-tiny{fill:var(--muted);font:11.5px ui-sans-serif,system-ui,sans-serif}
  .d-mono{fill:var(--fg);font:12.5px ui-monospace,SFMono-Regular,Menlo,monospace}
  .d-ok{fill:var(--ok);font:600 12.5px ui-sans-serif,system-ui,sans-serif}
  .d-bad{fill:var(--bad);font:600 12.5px ui-sans-serif,system-ui,sans-serif}
  .split{display:flex;gap:1.5rem;flex-wrap:wrap;align-items:flex-start}
  .split>*{flex:1;min-width:16rem}
  .qr{max-width:160px;border-radius:12px;border:1px solid var(--line);display:block}
  .note{border-left:3px solid var(--accent);background:var(--card);border-radius:0 10px 10px 0;
    padding:.85rem 1.1rem;margin:1.25rem 0;font-size:.93rem}
  .note.warn{border-left-color:var(--bad)}
  .note.good{border-left-color:var(--ok)}
  .flow{display:flex;align-items:center;gap:1rem;flex-wrap:wrap;border:1px solid var(--line);
    background:var(--card);border-radius:14px;padding:1.1rem 1.25rem;margin:1rem 0}
  .flow .node{flex:1;min-width:12rem}
  .flow .node .t{font-weight:650}
  .flow .node .p{color:var(--muted);font-size:.8rem;word-break:break-all}
  .arrow{color:var(--accent);font-weight:650;text-align:center;font-size:.82rem;min-width:10rem}
  ul,ol.spaced{margin:.7rem 0 .7rem 1.3rem}
  li{margin:.3rem 0}
  footer{margin-top:4rem;padding-top:1.5rem;border-top:1px solid var(--line);color:var(--muted);font-size:.88rem}
</style></head><body><main>

<header>
  <h1>Wolffish Relay</h1>
  <p class="lede">The zero-retention meeting point that carries encrypted traffic between your desktop and your phone — and cannot read, keep, or log any of it.</p>
  <div class="badges">
    <span class="badge ${ok ? 'pass' : 'fail'}"><span class="dot"></span>${ok ? `example run: ${run.passed}/${run.passed + run.failed} checks passed` : `${run.failed} checks failed`}</span>
    <span class="badge">MIT</span>
    <span class="badge">Cloudflare Workers</span>
    <span class="badge mono">${esc(run.relayUrl)}</span>
  </div>
</header>

<nav class="toc">
  <ol>
    <li><a href="#how">How it works</a></li>
    <li><a href="#built">How it's built</a></li>
    <li><a href="#contract">The wire contract</a></li>
    <li><a href="#moving">Moving data and files</a></li>
    <li><a href="#security">Security promises</a></li>
    <li><a href="#zdr">Zero data retention</a></li>
    <li><a href="#logs">No logs, no telemetry</a></li>
    <li><a href="#run">Example run</a></li>
    <li><a href="#selfhost">Run your own relay</a></li>
  </ol>
</nav>

<h2 id="how">How it works</h2>
<p>Two devices need to talk. One sits behind a home router, the other behind a mobile carrier's NAT; neither can accept an incoming connection. So both dial <em>outward</em> to the same address and meet there. That address is the relay.</p>

<figure>${topology()}<figcaption>Neither device listens for connections. They meet in the middle, and the middle can't read what passes through it.</figcaption></figure>

<p>The relay's whole job is to notice that two sockets presented the same rendezvous ID and to pass bytes between them. It performs no authentication of its own, keeps no accounts, and holds nothing once the sockets close. Everything that makes the tunnel <em>safe</em> happens on the devices, before a byte is handed over.</p>

<h3>Pairing happens once, by QR</h3>
<div class="split">
  <div>
    <p>The desktop displays a QR code carrying three things: the relay URL, its own long-lived public key, and a freshly generated 32-byte pairing secret. The phone's camera reads it.</p>
    <p>That camera hop matters more than it looks. Because the secret travels <strong>out of band</strong> — screen to lens, never over the network — a hostile relay cannot insert itself into the pairing. It never sees the secret, so it can never complete the handshake in the middle.</p>
    <p>From that secret both devices derive the same rendezvous ID: <code>rid = HMAC(secret, "rid-v1")</code>. It is 256 bits, unguessable, and the only fact about a pairing the relay ever learns. It identifies a meeting, not a person.</p>
  </div>
  <div style="flex:0 0 auto">
    <img class="qr" src="${QR_ILLUSTRATION}" alt="Example pairing QR code" width="160" height="160" />
    <p class="muted" style="font-size:.8rem;text-align:center;margin-top:.5rem">illustrative — each pairing<br />generates a fresh one</p>
  </div>
</div>

<h3>Then a handshake, every time they reconnect</h3>
<p>Pairing is once. Reconnecting is automatic and needs no user action: the devices already hold each other's keys, so they run a <strong>Noise IKpsk2</strong> handshake — the pattern designed for exactly this asymmetry, where the initiator already knows the responder's static key but not vice versa.</p>

<figure>${handshake()}<figcaption>Two messages, one round trip. The pairing secret enters as the PSK, binding the session to the device that scanned the code.</figcaption></figure>

<p>Three properties fall out of it. <strong>Mutual authentication:</strong> each side proves possession of its long-term key, and the desktop pins the phone's key on first contact. <strong>Forward secrecy:</strong> fresh ephemeral keys per session mean a key stolen next year cannot decrypt traffic captured today. <strong>Pairing binding:</strong> the PSK means knowing the rendezvous ID is not enough — an attacker who somehow learns it still cannot complete a handshake.</p>

<h2 id="built">How it's built</h2>
<p>The entire cloud footprint is one Worker script containing one Durable Object class — about 250 lines. There is no server, no container, no database, and nothing to patch.</p>

<div class="wrap"><table>
<thead><tr><th>File</th><th>Role</th></tr></thead>
<tbody>
<tr><td><code>src/index.ts</code></td><td>Stateless front door: validates the URL shape and the role, then routes to the one Durable Object that owns this rendezvous ID</td></tr>
<tr><td><code>src/tunnel.ts</code></td><td>The Durable Object: pairs the two roles, forwards binary frames verbatim, replaces zombie sockets, enforces limits</td></tr>
<tr><td><code>src/protocol.ts</code></td><td>The wire contract in one file — ID format, roles, frame cap, keepalive, close codes, presence notices</td></tr>
<tr><td><code>wrangler.jsonc</code></td><td>Configuration, and where the retention guarantees are pinned so a deploy re-asserts them</td></tr>
</tbody></table></div>

<h3>Why a Durable Object</h3>
<p>A plain Worker is stateless by design: two requests can land on two machines in two cities that share nothing. If both devices simply "connected to the Worker", they would land on unrelated instances and never find each other.</p>
<p>A Durable Object adds exactly one thing: <strong>named single-instance routing</strong>. Every request for a given name reaches the same one running instance, anywhere on earth. That is what lets two sockets be in the same place at the same time. "Durable" refers to that stable identity — not to storage. A Durable Object <em>may</em> attach persistent storage; this one simply never calls it.</p>

<div class="note">The relay uses the WebSocket <strong>Hibernation API</strong>, so an idle tunnel is evicted from memory entirely and costs nothing while a desktop sits parked. Connection state lives inside the sockets themselves, never in instance fields — and eviction is the whole cleanup story.</div>

<h2 id="contract">The wire contract</h2>
<div class="wrap"><table>
<thead><tr><th>Route</th><th>Behaviour</th></tr></thead>
<tbody>
<tr><td><code>GET /t/&lt;rid&gt;?role=host|guest</code> + upgrade</td><td>Join the tunnel for that rendezvous ID</td></tr>
<tr><td><code>GET /healthz</code></td><td><code>200 ok</code></td></tr>
<tr><td><code>GET /</code></td><td>Status page</td></tr>
<tr><td>anything else</td><td><code>404</code> / <code>400</code> / <code>405</code> / <code>426</code></td></tr>
</tbody></table></div>

<p><code>rid</code> must match <code>^[0-9a-f]{64}$</code>. The desktop connects as <code>host</code> — the parked, always-on side. The phone connects as <code>guest</code>.</p>

<h3>Frames</h3>
<ul>
  <li><strong>Binary frames are peer data</strong>: opaque sealed records, forwarded verbatim to the other role, capped at 1 MiB each.</li>
  <li><strong>Text frames from the relay</strong> are presence notices, the only text it ever sends: <code>{"t":"peer-present"}</code> and <code>{"t":"peer-gone"}</code>.</li>
  <li><strong>Text from a client</strong>: exactly one is legal, the keepalive <code>ping</code> → <code>pong</code>, answered by the runtime without even waking the object. Anything else closes the connection.</li>
</ul>

<div class="wrap"><table>
<thead><tr><th>Close code</th><th>Meaning</th></tr></thead>
<tbody>
<tr><td><code>4000</code> Replaced</td><td>A newer connection for your role arrived; this socket was evicted</td></tr>
<tr><td><code>4400</code> ProtocolViolation</td><td>You sent a non-keepalive text frame</td></tr>
<tr><td><code>4413</code> MessageTooLarge</td><td>You sent a frame over 1 MiB</td></tr>
</tbody></table></div>

<p>Two semantics matter for client authors. One live socket per role — a reconnect <em>replaces</em> its predecessor, and the peer never sees a false "gone" during that swap. And frames sent while the peer is absent are <strong>dropped</strong>: presence notices tell you when someone is there, and delivery guarantees belong to the end-to-end protocol's acknowledgements, never to the relay.</p>

<h2 id="moving">Moving data and files</h2>
<p>Above the sealed frame layer sit three kinds of traffic, all multiplexed on the one socket: <strong>RPC</strong> (request/response — fetch the config, list conversations, run an agent turn), <strong>events</strong> (unsolicited pushes — streaming agent output, "this conversation changed"), and <strong>file transfer</strong>.</p>

<p>Files never move as files. They move as a stream of independently sealed chunks, which is what makes the transfer resumable, memory-flat, and verifiable.</p>

<figure>${fileFlow()}<figcaption>The sender holds a window, never the file. Memory stays flat whether the file is 3 MB or 300 GB.</figcaption></figure>

<p>Each chunk is encrypted on its own, so a corrupted or reordered one fails loudly and alone rather than poisoning the file. The receiver writes each chunk straight to disk at its offset and checkpoints its progress every sixteen chunks; if the connection dies, reconnecting replays the manifest and the receiver simply asks to continue from its checkpoint. When the last chunk lands, the whole-file hash is compared against the manifest before the file is made visible.</p>

<div class="note">There is no protocol size limit. The practical bounds are disk space on the receiving device and patience — a 1 GB file over a relay path is minutes, not seconds, and survives any number of interruptions along the way.</div>

<h2 id="security">Security promises</h2>
<p>The relay is <strong>untrusted by design</strong>. Every guarantee below holds even if the relay is fully compromised, run by someone else, or replaced by a hostile clone.</p>

<div class="wrap"><table>
<thead><tr><th>Promise</th><th>How it's achieved</th></tr></thead>
<tbody>
<tr><td><strong>Content is unreadable in transit</strong></td><td>Every frame is sealed on-device with ChaCha20-Poly1305 under keys the relay never sees</td></tr>
<tr><td><strong>Tampering is detected</strong></td><td>AEAD authentication on every frame — a single flipped bit fails the tag and the frame is discarded</td></tr>
<tr><td><strong>Replay and reordering fail</strong></td><td>Per-session keys with a strictly increasing nonce counter</td></tr>
<tr><td><strong>Past traffic stays safe</strong></td><td>Forward secrecy: fresh ephemeral keys per session, so a stolen device key cannot decrypt earlier sessions</td></tr>
<tr><td><strong>The relay cannot impersonate either device</strong></td><td>Mutual authentication against pinned static keys; the pairing secret it never saw is required to finish a handshake</td></tr>
<tr><td><strong>Pairing cannot be intercepted</strong></td><td>The secret travels out of band, screen to camera, and is mixed into the handshake as the PSK</td></tr>
<tr><td><strong>Strangers cannot join</strong></td><td>The rendezvous ID is 256 bits and unguessable; even holding it does not let an attacker complete a handshake</td></tr>
<tr><td><strong>Nothing survives the session</strong></td><td>No storage is ever written — see the retention section below</td></tr>
</tbody></table></div>

<h3>What a hostile relay could still do</h3>
<p>Stated plainly, because a security claim without its limits is marketing. A relay operator — including Cloudflare, including you if you self-host — can observe, while the sockets are live: the two IP addresses, the rendezvous ID, the timing of frames, and their sizes. It can also refuse service or drop frames.</p>
<p>It cannot read content, alter it undetected, replay it, forge a frame either device will accept, impersonate either side, or recover anything after disconnection. Traffic metadata is the irreducible cost of any relayed system; the design keeps it to the minimum and never records it.</p>

<h2 id="zdr">Zero data retention</h2>
<p>"We don't store your data" is a promise. This is the version you can check: an inventory of every piece of state in the system and where it lives.</p>

<figure>${stateMap()}<figcaption>All durable state sits on the two devices you own. The middle holds live sockets and nothing else.</figcaption></figure>

<div class="wrap"><table>
<thead><tr><th>State</th><th>Where it lives</th><th>Lifetime</th></tr></thead>
<tbody>
<tr><td>Device keypairs, peer public key, pairing secret</td><td>OS keychain on each device</td><td>Until you unpair</td></tr>
<tr><td>Conversations, configs, files, sync cursors</td><td>Each app's own local database</td><td>The product's own data — endpoints, not the pipe</td></tr>
<tr><td>Session keys</td><td>Both devices' RAM</td><td>One connection</td></tr>
<tr><td>The socket pair and a role tag</td><td>Relay RAM</td><td>Dies with the sockets</td></tr>
<tr><td>Any database, object store, queue or log</td><td class="bad">Does not exist</td><td>—</td></tr>
</tbody></table></div>

<p>Unpairing is deleting two keychain entries. There is nothing in the cloud to delete because nothing was ever written there — which is also why reconnection is free: there is no server-side session to restore, ever.</p>

<div class="note good"><strong>Measured, not asserted.</strong> After the example run below moved ${bytes(totals.bytes ?? 0)} through production, the relay's storage meters read <strong>0 B</strong> across every counter — SQL storage, key-value storage, rows read, rows written, storage operations. Compute happened; storage did not.</div>

<h2 id="logs">No logs, no telemetry</h2>
<p>Retention has a second face: even without a database, a service can leak everything through its logs. This one is configured so there is nothing to leak, and the settings live in version control so every deploy re-asserts them.</p>

<div class="wrap"><table>
<thead><tr><th>Surface</th><th>State</th></tr></thead>
<tbody>
<tr><td>Worker logs and traces</td><td class="ok">Disabled in <code>wrangler.jsonc</code> (<code>observability.enabled = false</code>)</td></tr>
<tr><td>Log export (Logpush)</td><td class="ok">No jobs configured</td></tr>
<tr><td><code>console.log</code> anywhere in the source</td><td class="ok">Not a single one</td></tr>
<tr><td>Error-tracking or analytics SDK</td><td class="ok">None — the Worker has no dependencies at runtime</td></tr>
<tr><td>Storage bindings (KV, D1, R2, queues, analytics engine)</td><td class="ok">None — the only binding is the Durable Object itself</td></tr>
<tr><td>Build-tool telemetry</td><td class="ok">Off (<code>send_metrics: false</code>)</td></tr>
<tr><td>Browser telemetry headers (NEL / report-to)</td><td class="ok">Switched off at the zone</td></tr>
<tr><td>Tail workers (a covert log path)</td><td class="ok">None connected</td></tr>
</tbody></table></div>

<p>What remains, honestly: the platform's own aggregate request counters, and TLS terminating at the edge — as it does for any hosted service. Neither exposes content, because what crosses the edge is already ciphertext sealed on your devices. If that residual matters to you, the design's answer is the last section: run the relay yourself.</p>

<h2 id="run">Example run</h2>
<p class="muted">Generated ${esc(run.generatedAt)} · a real cycle against <code>${esc(run.relayUrl)}</code>, not a simulation. Reproduce it with <code>npm run playground</code>.</p>

<div class="cards">
  <div class="card"><div class="k">Checks</div><div class="v ${ok ? 'ok' : 'bad'}">${run.passed}/${run.passed + run.failed}</div></div>
  <div class="card"><div class="k">Files delivered</div><div class="v">${totals.files ?? 0}</div></div>
  <div class="card"><div class="k">Payload moved</div><div class="v">${bytes(totals.bytes ?? 0)}</div></div>
  <div class="card"><div class="k">Sealed frames</div><div class="v">${(totals.frames ?? 0).toLocaleString()}</div></div>
  <div class="card"><div class="k">Handshake</div><div class="v">${run.handshakeMs ?? '—'} ms</div></div>
  <div class="card"><div class="k">Wall clock</div><div class="v">${duration(run.totalMs)}</div></div>
</div>

<p>One run drives the whole lifecycle the way the apps will: it stages real data from a live Wolffish workspace, pairs by QR, hand-shakes, audits the wire, tries to break in, syncs configuration and conversations, streams a real agent turn, and moves files — including a 248 MB PDF that is deliberately interrupted mid-flight to prove resume.</p>

${
  big
    ? `<h3>The big one — ${esc(big.name)}</h3>
<div class="flow">
  <div class="node"><div class="t">Desktop</div><div class="p">${bytes(big.size)}</div><div class="p">source of truth</div></div>
  <div class="arrow">── sealed, chunked ──▶<br />${esc(big.speed)}<br />${duration(big.ms)}${big.resumedFrom ? ` · resumed at chunk ${big.resumedFrom}` : ''}</div>
  <div class="node"><div class="t">Phone</div><div class="p">${bytes(big.size)}</div><div class="p ${big.ok ? 'ok' : 'bad'}">${big.ok ? 'sha256 verified identical' : 'MISMATCH'}</div></div>
</div>
<p class="muted" style="font-size:.9rem">The phone's socket was terminated outright partway through. It reconnected, ran a fresh handshake, asked to continue from its checkpoint, and finished — with the final hash matching the source byte for byte.</p>`
    : ''
}

<h3>Phases</h3>
<div class="wrap"><table>
<thead><tr><th>Phase</th><th>What it proves</th><th class="num">Checks</th><th class="num">Time</th></tr></thead>
<tbody>
${run.phases
  .map(
    (p) => `<tr><td>${esc(p.title)}</td><td class="muted">${esc(p.detail)}</td>
  <td class="num ${p.checks.every((c) => c.ok) ? 'ok' : 'bad'}">${p.checks.filter((c) => c.ok).length}/${p.checks.length}</td>
  <td class="num">${duration(p.ms ?? 0)}</td></tr>`
  )
  .join('\n')}
</tbody></table></div>

<h3>Transfers</h3>
<div class="wrap"><table>
<thead><tr><th>File</th><th>Origin</th><th class="num">Size</th><th class="num">Time</th><th class="num">Throughput</th><th>Result</th></tr></thead>
<tbody>
${run.transfers
  .map(
    (t) => `<tr><td><code>${esc(t.name)}</code></td><td class="muted">${esc(t.source ?? '')}</td>
  <td class="num">${bytes(t.size)}</td><td class="num">${duration(t.ms)}</td><td class="num">${esc(t.speed)}</td>
  <td class="${t.ok ? 'ok' : 'bad'}">${t.ok ? 'delivered' : 'failed'}${t.interrupted ? ' · resumed' : ''}</td></tr>`
  )
  .join('\n')}
</tbody></table></div>
<p class="muted" style="font-size:.88rem">Both endpoints run on one machine during the example, sharing a single uplink — read these as a floor, not a ceiling. Small files are latency-bound (two protocol round trips before the first byte); large files are bandwidth-bound.</p>

${
  run.evidence
    ? `<h3>What the relay actually carried</h3>
<p>These are the first bytes of real frames, captured at the socket boundary — exactly the bytes the relay forwarded during this run.</p>
${code(run.evidence.samples.map((s) => `${s.direction.padEnd(14)} ${String(s.bytes).padStart(8)} B  ${s.context.padEnd(14)} ${s.head}…`).join('\n'))}
<p>Across ${run.evidence.frames.toLocaleString()} frames and ${bytes(run.evidence.bytes)}, the captured ciphertext measures <strong>${run.evidence.entropy.toFixed(3)} bits per byte</strong> of entropy — 8.0 is indistinguishable from random noise. No plaintext marker searched for appears anywhere in it, including the <code>%PDF</code> header of the file being transferred at the time.</p>`
    : ''
}

<h3>Every check</h3>
<div class="wrap"><table>
<thead><tr><th></th><th>Assertion</th><th>Detail</th><th>Phase</th></tr></thead>
<tbody>
${run.checks
  .map(
    (c) => `<tr><td class="${c.ok ? 'ok' : 'bad'}">${c.ok ? '✓' : '✗'}</td><td>${esc(c.label)}</td>
  <td class="muted">${esc(c.detail)}</td><td class="muted">${esc(c.phase)}</td></tr>`
  )
  .join('\n')}
</tbody></table></div>

<h2 id="selfhost">Run your own relay</h2>
<p>The desktop and mobile apps let you point at any relay, because the relay URL travels inside the pairing QR. Change it there and the devices meet at your address instead — no other setting, no rebuild.</p>
<p>This is deliberate. Content security never depended on the relay's honesty, so swapping in your own costs you nothing and gains you full control of the metadata surface.</p>

<h3>Option A — your own Cloudflare deployment</h3>
<p>The same code, on your account, in about ten minutes.</p>
${code(`# 1. Fork or clone
git clone https://github.com/thewolffish/wolffish-relay.git
cd wolffish-relay && npm install

# 2. Point it at your own hostname
#    edit wrangler.jsonc → "routes": [{ "pattern": "relay.example.com", "custom_domain": true }]
#    (or delete "routes" and set "workers_dev": true to use a *.workers.dev address)

# 3. Deploy
npx wrangler login
npx wrangler deploy

# 4. Check it
curl https://relay.example.com/healthz    # → ok`)}
<p>To keep the retention guarantees, leave these exactly as they ship: <code>observability.enabled: false</code>, <code>send_metrics: false</code>, no storage bindings, and no Logpush job on the zone. If you deploy from CI instead of a laptop, the included GitHub Actions workflow needs only two secrets — a scoped API token and your account ID.</p>

<h3>Option B — anywhere that runs Node</h3>
<p>Nothing about the relay is Cloudflare-specific: it matches two sockets by name and forwards bytes. Here is the whole thing for a plain Node host, behind any TLS terminator you already run.</p>
${code(`import { WebSocketServer } from 'ws'   // npm i ws

const rooms = new Map()                  // rid → { host, guest }   RAM only, never persisted
const RID = /^[0-9a-f]{64}$/
const MAX = 1024 * 1024

new WebSocketServer({ port: 8787 }).on('connection', (ws, req) => {
  const url = new URL(req.url, 'http://x')
  const rid = url.pathname.match(/^\\/t\\/([0-9a-f]{64})$/)?.[1]
  const role = url.searchParams.get('role')
  if (!rid || !RID.test(rid) || (role !== 'host' && role !== 'guest')) return ws.close(1008)

  const room = rooms.get(rid) ?? {}
  room[role]?.close(4000, 'replaced')     // newest connection per role wins
  room[role] = ws
  rooms.set(rid, room)

  const peer = () => (role === 'host' ? room.guest : room.host)
  if (peer()?.readyState === 1) {
    ws.send('{"t":"peer-present"}')
    peer().send('{"t":"peer-present"}')
  }

  ws.on('message', (data, isBinary) => {
    if (!isBinary) return data.toString() === 'ping' ? ws.send('pong') : ws.close(4400)
    if (data.length > MAX) return ws.close(4413)
    if (peer()?.readyState === 1) peer().send(data, { binary: true })
  })

  ws.on('close', () => {
    if (room[role] === ws) delete room[role]
    if (peer()?.readyState === 1) peer().send('{"t":"peer-gone"}')
    if (!room.host && !room.guest) rooms.delete(rid)   // forget everything
  })
})`)}
<p>That is the complete contract. Serve it over TLS (<code>wss://</code>), keep access logs off if you want the retention story to hold, and make sure your proxy does not buffer or time out WebSocket upgrades.</p>

<div class="note warn"><strong>If you host it, you own the metadata.</strong> Content stays sealed either way, but connection times, IP addresses and frame sizes pass through your machine. Turn off access logging deliberately — most web servers record every connection by default, which would put back exactly what this design removes.</div>

<h3>Verifying your relay</h3>
${code(`# health
curl https://relay.example.com/healthz

# two terminals: presence and forwarding
npx wscat -c "wss://relay.example.com/t/$(printf 'a%.0s' {1..64})?role=host"
npx wscat -c "wss://relay.example.com/t/$(printf 'a%.0s' {1..64})?role=guest"
# both should print {"t":"peer-present"} the moment the second connects

# or drive the whole tunnel against it, end to end
npm run playground -- --relay wss://relay.example.com`)}
<p>That last command runs the complete cycle in this document — pairing, handshake, ciphertext audit, intrusion probes, file transfer with an interruption, and byte-for-byte verification — against your own deployment, and writes you a report just like this one.</p>

<footer>
  <p><strong>Wolffish Relay</strong> · MIT · <a href="https://github.com/thewolffish/wolffish-relay">github.com/thewolffish/wolffish-relay</a> · <a href="https://wolffi.sh">wolffi.sh</a></p>
  <p style="margin-top:.4rem">This document is regenerated by <code>npm run playground</code>, so its figures are measurements from a real run rather than claims.</p>
</footer>

</main></body></html>`
}
